version: '3.7'

services:
  app:
    build: .
    depends_on:
      - db
    network_mode: bridge
    container_name: app
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres